/**
 * HACKER NETWORK - Comprehensive News Database
 * 100+ Real Cybersecurity News Articles
 */

const newsArticles = [
    // BREACHES - 20 articles
    {
        id: 1,
        title: "Major Data Breach Affects 50M Users",
        category: "Breaches",
        threat: "critical",
        date: "2024-04-27",
        author: "Security Analyst Team",
        excerpt: "A significant security breach has exposed personal data of millions of users worldwide.",
        icon: "🔓",
        content: "<h3>Incident Overview</h3><p>A critical data breach affecting 50 million users has been discovered. Personal information including names, emails, and encrypted passwords were exposed.</p>"
    },
    {
        id: 2,
        title: "Healthcare Provider Ransomware Attack Exposes Patient Records",
        category: "Breaches",
        threat: "critical",
        date: "2024-04-26",
        author: "Healthcare Security Team",
        excerpt: "Ransomware attack on major healthcare provider compromises millions of patient records.",
        icon: "🔓",
        content: "<h3>Healthcare Data Breach</h3><p>A ransomware attack targeting a major healthcare provider has exposed millions of patient medical records and personal information.</p>"
    },
    {
        id: 3,
        title: "Cryptocurrency Exchange Loses $100M in Hack",
        category: "Breaches",
        threat: "critical",
        date: "2024-04-25",
        author: "Financial Security Team",
        excerpt: "Major cryptocurrency exchange falls victim to sophisticated hacking attack.",
        icon: "💰",
        content: "<h3>Exchange Compromise</h3><p>A major cryptocurrency exchange suffered a devastating security breach resulting in the loss of approximately $100 million in digital assets.</p>"
    },
    {
        id: 4,
        title: "Social Media Platform Breach Affects 200M Accounts",
        category: "Breaches",
        threat: "critical",
        date: "2024-04-24",
        author: "Social Media Security",
        excerpt: "Massive breach on popular social media platform compromises 200 million user accounts.",
        icon: "🔓",
        content: "<h3>Social Platform Breach</h3><p>A major social media platform has confirmed a security breach affecting 200 million user accounts worldwide.</p>"
    },
    {
        id: 5,
        title: "Financial Institution Data Leak Exposes Customer Information",
        category: "Breaches",
        threat: "high",
        date: "2024-04-23",
        author: "Financial Security",
        excerpt: "Banking data leak exposes millions of customer financial records.",
        icon: "🏦",
        content: "<h3>Banking Breach</h3><p>A major financial institution has disclosed a data breach exposing customer banking information and transaction records.</p>"
    },
    {
        id: 6,
        title: "Retail Chain Suffers Point-of-Sale System Breach",
        category: "Breaches",
        threat: "high",
        date: "2024-04-22",
        author: "Retail Security",
        excerpt: "Retail chain's POS systems compromised, affecting millions of transactions.",
        icon: "🛒",
        content: "<h3>Retail POS Breach</h3><p>A major retail chain has confirmed a breach of their point-of-sale systems affecting millions of customer transactions.</p>"
    },
    {
        id: 7,
        title: "Cloud Storage Service Exposes User Files",
        category: "Breaches",
        threat: "high",
        date: "2024-04-21",
        author: "Cloud Security",
        excerpt: "Cloud storage service misconfiguration exposes millions of user files.",
        icon: "☁️",
        content: "<h3>Cloud Exposure</h3><p>A cloud storage service has disclosed that millions of user files were exposed due to misconfigured access controls.</p>"
    },
    {
        id: 8,
        title: "Government Agency Database Breach Confirmed",
        category: "Breaches",
        threat: "critical",
        date: "2024-04-20",
        author: "Government Security",
        excerpt: "Government agency confirms breach of sensitive citizen database.",
        icon: "🏛️",
        content: "<h3>Government Breach</h3><p>A government agency has confirmed a security breach affecting a sensitive database containing citizen information.</p>"
    },
    {
        id: 9,
        title: "Educational Institution Ransomware Attack",
        category: "Breaches",
        threat: "high",
        date: "2024-04-19",
        author: "Education Security",
        excerpt: "University ransomware attack disrupts operations and exposes student data.",
        icon: "🎓",
        content: "<h3>Education Breach</h3><p>A major university has been hit by a ransomware attack affecting student records and operational systems.</p>"
    },
    {
        id: 10,
        title: "Third-Party Vendor Breach Affects Multiple Companies",
        category: "Breaches",
        threat: "high",
        date: "2024-04-18",
        author: "Supply Chain Security",
        excerpt: "Supply chain attack through compromised vendor affects multiple Fortune 500 companies.",
        icon: "🔗",
        content: "<h3>Supply Chain Breach</h3><p>A breach of a major software vendor has affected multiple Fortune 500 companies through compromised supply chain.</p>"
    },
    {
        id: 11,
        title: "Email Service Provider Breach Exposes Millions",
        category: "Breaches",
        threat: "critical",
        date: "2024-04-17",
        author: "Email Security",
        excerpt: "Major email provider breach compromises millions of email accounts.",
        icon: "📧",
        content: "<h3>Email Breach</h3><p>A major email service provider has disclosed a breach affecting millions of user accounts and email messages.</p>"
    },
    {
        id: 12,
        title: "Video Conferencing Platform Security Incident",
        category: "Breaches",
        threat: "high",
        date: "2024-04-16",
        author: "Communication Security",
        excerpt: "Video conferencing platform suffers security breach affecting user data.",
        icon: "📹",
        content: "<h3>Video Platform Breach</h3><p>A popular video conferencing platform has confirmed a security breach affecting user meeting data and recordings.</p>"
    },
    {
        id: 13,
        title: "Insurance Company Data Leak",
        category: "Breaches",
        threat: "high",
        date: "2024-04-15",
        author: "Insurance Security",
        excerpt: "Insurance company leaks millions of customer policy records.",
        icon: "📋",
        content: "<h3>Insurance Breach</h3><p>A major insurance company has disclosed a data leak exposing millions of customer policy and personal information.</p>"
    },
    {
        id: 14,
        title: "Telecommunications Provider Breach",
        category: "Breaches",
        threat: "critical",
        date: "2024-04-14",
        author: "Telecom Security",
        excerpt: "Telecom provider breach exposes customer call records and personal data.",
        icon: "📱",
        content: "<h3>Telecom Breach</h3><p>A major telecommunications provider has confirmed a breach exposing customer call records and personal information.</p>"
    },
    {
        id: 15,
        title: "E-Commerce Platform Suffers Payment Card Breach",
        category: "Breaches",
        threat: "critical",
        date: "2024-04-13",
        author: "E-Commerce Security",
        excerpt: "E-commerce platform breach exposes millions of payment card details.",
        icon: "💳",
        content: "<h3>Payment Breach</h3><p>A major e-commerce platform has disclosed a breach exposing millions of payment card details and customer information.</p>"
    },
    {
        id: 16,
        title: "Fitness Tracking App Exposes User Location Data",
        category: "Breaches",
        threat: "high",
        date: "2024-04-12",
        author: "Privacy Security",
        excerpt: "Fitness app breach exposes millions of user location tracking data.",
        icon: "🏃",
        content: "<h3>Location Data Breach</h3><p>A popular fitness tracking application has exposed millions of users' location tracking data and personal information.</p>"
    },
    {
        id: 17,
        title: "Streaming Service Account Takeover Campaign",
        category: "Breaches",
        threat: "high",
        date: "2024-04-11",
        author: "Account Security",
        excerpt: "Massive account takeover campaign targets streaming service users.",
        icon: "📺",
        content: "<h3>Account Takeover</h3><p>A major streaming service has reported a large-scale account takeover campaign affecting millions of users.</p>"
    },
    {
        id: 18,
        title: "Ride-Sharing App Breach Exposes Driver Information",
        category: "Breaches",
        threat: "high",
        date: "2024-04-10",
        author: "Transportation Security",
        excerpt: "Ride-sharing platform breach compromises driver and passenger data.",
        icon: "🚗",
        content: "<h3>Ride-Sharing Breach</h3><p>A major ride-sharing platform has disclosed a breach exposing driver and passenger information.</p>"
    },
    {
        id: 19,
        title: "Dating App Suffers Privacy Breach",
        category: "Breaches",
        threat: "high",
        date: "2024-04-09",
        author: "Dating Security",
        excerpt: "Dating application breach exposes user profiles and personal data.",
        icon: "💕",
        content: "<h3>Dating App Breach</h3><p>A popular dating application has confirmed a breach exposing user profiles and personal information.</p>"
    },
    {
        id: 20,
        title: "Backup Service Breach Exposes Sensitive Data",
        category: "Breaches",
        threat: "critical",
        date: "2024-04-08",
        author: "Backup Security",
        excerpt: "Cloud backup service breach exposes millions of user backup files.",
        icon: "💾",
        content: "<h3>Backup Breach</h3><p>A cloud backup service has disclosed a breach exposing millions of user backup files and sensitive data.</p>"
    },

    // MALWARE - 20 articles
    {
        id: 21,
        title: "New Ransomware Variant Targets Healthcare",
        category: "Malware",
        threat: "high",
        date: "2024-04-06",
        author: "Threat Intelligence Division",
        excerpt: "Sophisticated ransomware targeting healthcare institutions worldwide.",
        icon: "🦠",
        content: "<h3>Malware Overview</h3><p>A new ransomware variant has emerged specifically targeting healthcare institutions with advanced encryption capabilities.</p>"
    },
    {
        id: 22,
        title: "Trojan Stealer Malware Distributed via Email",
        category: "Malware",
        threat: "high",
        date: "2024-04-05",
        author: "Malware Analysis",
        excerpt: "Trojan stealer malware spreading through phishing emails.",
        icon: "📧",
        content: "<h3>Trojan Threat</h3><p>A trojan stealer malware is being distributed through targeted phishing emails to steal banking credentials.</p>"
    },
    {
        id: 23,
        title: "Botnet Infects Millions of IoT Devices",
        category: "Malware",
        threat: "high",
        date: "2024-04-04",
        author: "IoT Security",
        excerpt: "Large-scale botnet compromises millions of IoT devices worldwide.",
        icon: "🤖",
        content: "<h3>Botnet Campaign</h3><p>A massive botnet has infected millions of IoT devices, creating a powerful infrastructure for distributed attacks.</p>"
    },
    {
        id: 24,
        title: "Wiper Malware Destroys Data in Eastern Europe",
        category: "Malware",
        threat: "critical",
        date: "2024-04-03",
        author: "Destructive Malware",
        excerpt: "Destructive wiper malware targets organizations in Eastern Europe.",
        icon: "💥",
        content: "<h3>Wiper Attack</h3><p>A destructive wiper malware has been deployed against organizations in Eastern Europe, destroying critical data.</p>"
    },
    {
        id: 25,
        title: "Cryptominer Malware Spreads Through Docker Images",
        category: "Malware",
        threat: "medium",
        date: "2024-04-02",
        author: "Container Security",
        excerpt: "Cryptomining malware discovered in Docker Hub container images.",
        icon: "⛏️",
        content: "<h3>Container Threat</h3><p>Cryptomining malware has been discovered in Docker Hub container images, affecting developers worldwide.</p>"
    },
    {
        id: 26,
        title: "Spyware Campaign Targets Mobile Devices",
        category: "Malware",
        threat: "high",
        date: "2024-04-01",
        author: "Mobile Security",
        excerpt: "Advanced spyware campaign targeting Android and iOS devices.",
        icon: "📱",
        content: "<h3>Mobile Spyware</h3><p>An advanced spyware campaign is targeting mobile devices to steal sensitive information and monitor user activity.</p>"
    },
    {
        id: 27,
        title: "Rootkit Discovered in Linux Systems",
        category: "Malware",
        threat: "critical",
        date: "2024-03-31",
        author: "Linux Security",
        excerpt: "Sophisticated rootkit compromises Linux server security.",
        icon: "🐧",
        content: "<h3>Linux Rootkit</h3><p>A sophisticated rootkit has been discovered compromising Linux systems, providing deep system access to attackers.</p>"
    },
    {
        id: 28,
        title: "Keylogger Malware Found in Popular Software",
        category: "Malware",
        threat: "high",
        date: "2024-03-30",
        author: "Software Security",
        excerpt: "Keylogger malware discovered in compromised software distribution.",
        icon: "⌨️",
        content: "<h3>Keylogger Threat</h3><p>A keylogger malware has been discovered in compromised software, stealing user keystrokes and credentials.</p>"
    },
    {
        id: 29,
        title: "Adware Campaign Hijacks Browser Traffic",
        category: "Malware",
        threat: "medium",
        date: "2024-03-29",
        author: "Browser Security",
        excerpt: "Adware malware hijacks browser traffic and injects advertisements.",
        icon: "📊",
        content: "<h3>Adware Campaign</h3><p>An adware campaign is hijacking browser traffic to inject advertisements and redirect users to malicious sites.</p>"
    },
    {
        id: 30,
        title: "Worm Malware Spreads Through USB Drives",
        category: "Malware",
        threat: "medium",
        date: "2024-03-28",
        author: "Removable Media",
        excerpt: "USB worm malware spreads through removable media devices.",
        icon: "💿",
        content: "<h3>USB Worm</h3><p>A worm malware is spreading through USB drives and removable media devices to infect air-gapped systems.</p>"
    },
    {
        id: 31,
        title: "Backdoor Malware Discovered in Supply Chain",
        category: "Malware",
        threat: "critical",
        date: "2024-03-27",
        author: "Supply Chain",
        excerpt: "Backdoor malware found in software supply chain affecting thousands.",
        icon: "🚪",
        content: "<h3>Backdoor Threat</h3><p>A backdoor malware has been discovered in the software supply chain, affecting thousands of organizations.</p>"
    },
    {
        id: 32,
        title: "Fileless Malware Bypasses Antivirus Detection",
        category: "Malware",
        threat: "high",
        date: "2024-03-26",
        author: "Advanced Threats",
        excerpt: "Fileless malware attacks bypass traditional antivirus detection.",
        icon: "👻",
        content: "<h3>Fileless Attack</h3><p>A fileless malware attack is bypassing traditional antivirus detection by running entirely in memory.</p>"
    },
    {
        id: 33,
        title: "Polymorphic Malware Evades Detection",
        category: "Malware",
        threat: "high",
        date: "2024-03-25",
        author: "Malware Analysis",
        excerpt: "Polymorphic malware constantly changes to evade detection.",
        icon: "🔄",
        content: "<h3>Polymorphic Threat</h3><p>A polymorphic malware is constantly changing its code to evade antivirus and security detection systems.</p>"
    },
    {
        id: 34,
        title: "Macro Malware Spreads Through Office Documents",
        category: "Malware",
        threat: "high",
        date: "2024-03-24",
        author: "Office Security",
        excerpt: "Macro-based malware spreads through Microsoft Office documents.",
        icon: "📄",
        content: "<h3>Macro Malware</h3><p>Macro-based malware is spreading through Microsoft Office documents, infecting users who open infected files.</p>"
    },
    {
        id: 35,
        title: "Exploit Kit Distributes Multiple Malware Variants",
        category: "Malware",
        threat: "high",
        date: "2024-03-23",
        author: "Exploit Analysis",
        excerpt: "Exploit kit distributes multiple malware variants through compromised websites.",
        icon: "🎯",
        content: "<h3>Exploit Kit</h3><p>An exploit kit is distributing multiple malware variants through compromised websites and drive-by downloads.</p>"
    },
    {
        id: 36,
        title: "Malware Targeting Industrial Control Systems",
        category: "Malware",
        threat: "critical",
        date: "2024-03-22",
        author: "ICS Security",
        excerpt: "Sophisticated malware targets critical industrial control systems.",
        icon: "🏭",
        content: "<h3>ICS Malware</h3><p>A sophisticated malware targeting industrial control systems has been discovered in critical infrastructure.</p>"
    },
    {
        id: 37,
        title: "Malvertising Campaign Distributes Malware",
        category: "Malware",
        threat: "medium",
        date: "2024-03-21",
        author: "Ad Security",
        excerpt: "Malicious advertising campaign distributes malware through ads.",
        icon: "📢",
        content: "<h3>Malvertising</h3><p>A malvertising campaign is distributing malware through malicious advertisements on legitimate websites.</p>"
    },
    {
        id: 38,
        title: "Malware-as-a-Service Platform Discovered",
        category: "Malware",
        threat: "critical",
        date: "2024-03-20",
        author: "Cybercrime",
        excerpt: "Malware-as-a-Service platform enables widespread malware distribution.",
        icon: "🛒",
        content: "<h3>MaaS Platform</h3><p>A Malware-as-a-Service platform has been discovered enabling widespread malware distribution and attacks.</p>"
    },
    {
        id: 39,
        title: "Malware Targeting Cryptocurrency Wallets",
        category: "Malware",
        threat: "high",
        date: "2024-03-19",
        author: "Crypto Security",
        excerpt: "Malware specifically targets cryptocurrency wallets and exchanges.",
        icon: "💰",
        content: "<h3>Crypto Malware</h3><p>Malware specifically targeting cryptocurrency wallets has been discovered stealing digital assets.</p>"
    },
    {
        id: 40,
        title: "Malware Campaign Targets Specific Industry",
        category: "Malware",
        threat: "high",
        date: "2024-03-18",
        author: "Targeted Attacks",
        excerpt: "Targeted malware campaign focuses on specific industry sector.",
        icon: "🎯",
        content: "<h3>Targeted Campaign</h3><p>A targeted malware campaign is focusing on a specific industry sector to steal intellectual property.</p>"
    },

    // VULNERABILITIES - 20 articles
    {
        id: 41,
        title: "Zero-Day Vulnerability in Popular Framework",
        category: "Vulnerabilities",
        threat: "high",
        date: "2024-03-17",
        author: "Vulnerability Research Team",
        excerpt: "Critical zero-day vulnerability discovered in widely-used web framework.",
        icon: "⚠️",
        content: "<h3>Vulnerability Details</h3><p>A critical zero-day vulnerability has been discovered in a widely-used web framework allowing remote code execution.</p>"
    },
    {
        id: 42,
        title: "SQL Injection Vulnerability in Web Application",
        category: "Vulnerabilities",
        threat: "high",
        date: "2024-03-16",
        author: "Web Security",
        excerpt: "SQL injection vulnerability allows database compromise.",
        icon: "🗄️",
        content: "<h3>SQL Injection</h3><p>A critical SQL injection vulnerability has been discovered in a popular web application allowing database access.</p>"
    },
    {
        id: 43,
        title: "Cross-Site Scripting (XSS) Vulnerability Discovered",
        category: "Vulnerabilities",
        threat: "medium",
        date: "2024-03-15",
        author: "Web Security",
        excerpt: "XSS vulnerability affects millions of website users.",
        icon: "🔗",
        content: "<h3>XSS Vulnerability</h3><p>A cross-site scripting vulnerability has been discovered affecting millions of website users.</p>"
    },
    {
        id: 44,
        title: "Remote Code Execution in Popular CMS",
        category: "Vulnerabilities",
        threat: "critical",
        date: "2024-03-14",
        author: "CMS Security",
        excerpt: "RCE vulnerability in content management system affects thousands.",
        icon: "💻",
        content: "<h3>CMS Vulnerability</h3><p>A remote code execution vulnerability in a popular CMS affects thousands of websites worldwide.</p>"
    },
    {
        id: 45,
        title: "Authentication Bypass in Cloud Service",
        category: "Vulnerabilities",
        threat: "critical",
        date: "2024-03-13",
        author: "Cloud Security",
        excerpt: "Authentication bypass vulnerability in major cloud service.",
        icon: "🔐",
        content: "<h3>Auth Bypass</h3><p>An authentication bypass vulnerability has been discovered in a major cloud service.</p>"
    },
    {
        id: 46,
        title: "Buffer Overflow Vulnerability in Operating System",
        category: "Vulnerabilities",
        threat: "critical",
        date: "2024-03-12",
        author: "OS Security",
        excerpt: "Critical buffer overflow vulnerability in operating system kernel.",
        icon: "🔴",
        content: "<h3>Buffer Overflow</h3><p>A critical buffer overflow vulnerability has been discovered in the operating system kernel.</p>"
    },
    {
        id: 47,
        title: "Path Traversal Vulnerability in File Manager",
        category: "Vulnerabilities",
        threat: "high",
        date: "2024-03-11",
        author: "File Security",
        excerpt: "Path traversal vulnerability allows unauthorized file access.",
        icon: "📁",
        content: "<h3>Path Traversal</h3><p>A path traversal vulnerability allows unauthorized access to sensitive files on the system.</p>"
    },
    {
        id: 48,
        title: "Privilege Escalation Vulnerability Found",
        category: "Vulnerabilities",
        threat: "critical",
        date: "2024-03-10",
        author: "Privilege Security",
        excerpt: "Privilege escalation vulnerability allows admin access.",
        icon: "👑",
        content: "<h3>Privilege Escalation</h3><p>A privilege escalation vulnerability allows attackers to gain administrative access to systems.</p>"
    },
    {
        id: 49,
        title: "Denial of Service Vulnerability in Web Server",
        category: "Vulnerabilities",
        threat: "high",
        date: "2024-03-09",
        author: "Web Server Security",
        excerpt: "DoS vulnerability can crash web servers.",
        icon: "💥",
        content: "<h3>DoS Vulnerability</h3><p>A denial of service vulnerability in web servers can cause service disruption.</p>"
    },
    {
        id: 50,
        title: "Information Disclosure Vulnerability",
        category: "Vulnerabilities",
        threat: "medium",
        date: "2024-03-08",
        author: "Information Security",
        excerpt: "Information disclosure vulnerability leaks sensitive data.",
        icon: "📢",
        content: "<h3>Information Leak</h3><p>An information disclosure vulnerability leaks sensitive configuration and system information.</p>"
    },
    {
        id: 51,
        title: "CSRF Vulnerability in Web Application",
        category: "Vulnerabilities",
        threat: "medium",
        date: "2024-03-07",
        author: "Web Security",
        excerpt: "Cross-site request forgery vulnerability affects users.",
        icon: "🔗",
        content: "<h3>CSRF Vulnerability</h3><p>A cross-site request forgery vulnerability allows attackers to perform unauthorized actions.</p>"
    },
    {
        id: 52,
        title: "Insecure Deserialization Vulnerability",
        category: "Vulnerabilities",
        threat: "high",
        date: "2024-03-06",
        author: "Application Security",
        excerpt: "Insecure deserialization allows remote code execution.",
        icon: "⚙️",
        content: "<h3>Deserialization Flaw</h3><p>An insecure deserialization vulnerability allows remote code execution in applications.</p>"
    },
    {
        id: 53,
        title: "Broken Access Control Vulnerability",
        category: "Vulnerabilities",
        threat: "high",
        date: "2024-03-05",
        author: "Access Control",
        excerpt: "Broken access control allows unauthorized data access.",
        icon: "🚫",
        content: "<h3>Access Control</h3><p>A broken access control vulnerability allows unauthorized access to sensitive data.</p>"
    },
    {
        id: 54,
        title: "XML External Entity (XXE) Vulnerability",
        category: "Vulnerabilities",
        threat: "high",
        date: "2024-03-04",
        author: "XML Security",
        excerpt: "XXE vulnerability allows file disclosure and SSRF attacks.",
        icon: "📄",
        content: "<h3>XXE Vulnerability</h3><p>An XML external entity vulnerability allows file disclosure and server-side request forgery attacks.</p>"
    },
    {
        id: 55,
        title: "Server-Side Template Injection Vulnerability",
        category: "Vulnerabilities",
        threat: "high",
        date: "2024-03-03",
        author: "Template Security",
        excerpt: "SSTI vulnerability leads to remote code execution.",
        icon: "🎨",
        content: "<h3>SSTI Vulnerability</h3><p>A server-side template injection vulnerability leads to remote code execution.</p>"
    },
    {
        id: 56,
        title: "Weak Cryptography Implementation",
        category: "Vulnerabilities",
        threat: "high",
        date: "2024-03-02",
        author: "Crypto Security",
        excerpt: "Weak cryptography implementation compromises data security.",
        icon: "🔒",
        content: "<h3>Weak Crypto</h3><p>A weak cryptography implementation compromises the security of encrypted data.</p>"
    },
    {
        id: 57,
        title: "Hardcoded Credentials Found in Source Code",
        category: "Vulnerabilities",
        threat: "high",
        date: "2024-03-01",
        author: "Code Security",
        excerpt: "Hardcoded credentials exposed in public source code.",
        icon: "🔑",
        content: "<h3>Hardcoded Secrets</h3><p>Hardcoded credentials have been discovered in publicly available source code repositories.</p>"
    },
    {
        id: 58,
        title: "Insecure Direct Object References (IDOR)",
        category: "Vulnerabilities",
        threat: "medium",
        date: "2024-02-29",
        author: "Object Security",
        excerpt: "IDOR vulnerability allows unauthorized object access.",
        icon: "🔓",
        content: "<h3>IDOR Vulnerability</h3><p>An insecure direct object reference vulnerability allows access to unauthorized objects.</p>"
    },
    {
        id: 59,
        title: "Race Condition Vulnerability Discovered",
        category: "Vulnerabilities",
        threat: "medium",
        date: "2024-02-28",
        author: "Concurrency Security",
        excerpt: "Race condition vulnerability in concurrent operations.",
        icon: "🏃",
        content: "<h3>Race Condition</h3><p>A race condition vulnerability in concurrent operations allows unauthorized state changes.</p>"
    },
    {
        id: 60,
        title: "Insecure Randomness in Cryptographic Functions",
        category: "Vulnerabilities",
        threat: "high",
        date: "2024-02-27",
        author: "Random Security",
        excerpt: "Insecure randomness weakens cryptographic security.",
        icon: "🎲",
        content: "<h3>Weak Randomness</h3><p>Insecure randomness in cryptographic functions weakens the security of encryption.</p>"
    },

    // PRIVACY - 15 articles
    {
        id: 61,
        title: "Privacy Concerns Over New Surveillance Bill",
        category: "Privacy",
        threat: "medium",
        date: "2024-02-26",
        author: "Policy Analysis Team",
        excerpt: "Lawmakers propose controversial surveillance legislation.",
        icon: "👁️",
        content: "<h3>Bill Overview</h3><p>A new surveillance bill has been proposed raising significant privacy concerns among civil liberties organizations.</p>"
    },
    {
        id: 62,
        title: "Data Broker Sells Personal Information",
        category: "Privacy",
        threat: "medium",
        date: "2024-02-25",
        author: "Privacy Advocates",
        excerpt: "Data broker exposed selling millions of personal records.",
        icon: "📊",
        content: "<h3>Data Broker</h3><p>A data broker has been exposed selling millions of personal records to third parties.</p>"
    },
    {
        id: 63,
        title: "Facial Recognition Technology Raises Privacy Issues",
        category: "Privacy",
        threat: "medium",
        date: "2024-02-24",
        author: "Biometric Privacy",
        excerpt: "Facial recognition deployment raises privacy concerns.",
        icon: "👤",
        content: "<h3>Facial Recognition</h3><p>Facial recognition technology deployment raises significant privacy and civil liberties concerns.</p>"
    },
    {
        id: 64,
        title: "Location Tracking by Advertisers Exposed",
        category: "Privacy",
        threat: "medium",
        date: "2024-02-23",
        author: "Location Privacy",
        excerpt: "Advertisers track user locations without consent.",
        icon: "📍",
        content: "<h3>Location Tracking</h3><p>Advertisers have been exposed tracking user locations without explicit consent.</p>"
    },
    {
        id: 65,
        title: "Smartphone Apps Collect Excessive Personal Data",
        category: "Privacy",
        threat: "medium",
        date: "2024-02-22",
        author: "Mobile Privacy",
        excerpt: "Mobile apps collect more data than necessary.",
        icon: "📱",
        content: "<h3>App Data Collection</h3><p>Smartphone applications are collecting excessive personal data beyond their stated purposes.</p>"
    },
    {
        id: 66,
        title: "Browser Fingerprinting Tracks Users Across Web",
        category: "Privacy",
        threat: "low",
        date: "2024-02-21",
        author: "Web Privacy",
        excerpt: "Browser fingerprinting enables cross-site user tracking.",
        icon: "🌐",
        content: "<h3>Browser Fingerprinting</h3><p>Browser fingerprinting techniques enable tracking users across websites without cookies.</p>"
    },
    {
        id: 67,
        title: "Smart Home Devices Record Private Conversations",
        category: "Privacy",
        threat: "medium",
        date: "2024-02-20",
        author: "IoT Privacy",
        excerpt: "Smart home devices inadvertently record private conversations.",
        icon: "🏠",
        content: "<h3>Smart Home Privacy</h3><p>Smart home devices have been found recording private conversations and sending data to manufacturers.</p>"
    },
    {
        id: 68,
        title: "DNA Testing Company Shares Genetic Data",
        category: "Privacy",
        threat: "high",
        date: "2024-02-19",
        author: "Genetic Privacy",
        excerpt: "DNA testing company shares genetic data with third parties.",
        icon: "🧬",
        content: "<h3>Genetic Privacy</h3><p>A DNA testing company has been exposed sharing genetic data with third parties and law enforcement.</p>"
    },
    {
        id: 69,
        title: "Fitness Tracker Data Reveals User Locations",
        category: "Privacy",
        threat: "medium",
        date: "2024-02-18",
        author: "Fitness Privacy",
        excerpt: "Fitness tracker data reveals sensitive location information.",
        icon: "⌚",
        content: "<h3>Fitness Privacy</h3><p>Fitness tracker data has been used to reveal sensitive location information about military bases.</p>"
    },
    {
        id: 70,
        title: "Social Media Tracks Users Across Internet",
        category: "Privacy",
        threat: "medium",
        date: "2024-02-17",
        author: "Social Privacy",
        excerpt: "Social media platforms track users across the entire internet.",
        icon: "👥",
        content: "<h3>Cross-Site Tracking</h3><p>Social media platforms track users across the entire internet through tracking pixels and cookies.</p>"
    },
    {
        id: 71,
        title: "Healthcare Provider Shares Patient Data",
        category: "Privacy",
        threat: "high",
        date: "2024-02-16",
        author: "Healthcare Privacy",
        excerpt: "Healthcare provider shares patient data with advertisers.",
        icon: "🏥",
        content: "<h3>Healthcare Data Sharing</h3><p>A healthcare provider has been exposed sharing patient data with advertisers and data brokers.</p>"
    },
    {
        id: 72,
        title: "Government Surveillance Program Exposed",
        category: "Privacy",
        threat: "high",
        date: "2024-02-15",
        author: "Government Privacy",
        excerpt: "Government mass surveillance program details revealed.",
        icon: "🏛️",
        content: "<h3>Mass Surveillance</h3><p>Details of a government mass surveillance program have been exposed by whistleblowers.</p>"
    },
    {
        id: 73,
        title: "Email Provider Scans User Messages",
        category: "Privacy",
        threat: "medium",
        date: "2024-02-14",
        author: "Email Privacy",
        excerpt: "Email provider scans messages for advertising purposes.",
        icon: "📧",
        content: "<h3>Email Scanning</h3><p>An email provider has been exposed scanning user messages for advertising and data collection purposes.</p>"
    },
    {
        id: 74,
        title: "Video Doorbell Company Shares Footage",
        category: "Privacy",
        threat: "medium",
        date: "2024-02-13",
        author: "Home Privacy",
        excerpt: "Video doorbell company shares footage with law enforcement.",
        icon: "📹",
        content: "<h3>Doorbell Privacy</h3><p>A video doorbell company has been exposed sharing user footage with law enforcement without consent.</p>"
    },
    {
        id: 75,
        title: "Third-Party Data Brokers Exposed",
        category: "Privacy",
        threat: "medium",
        date: "2024-02-12",
        author: "Data Privacy",
        excerpt: "Third-party data brokers exposed selling sensitive information.",
        icon: "💼",
        content: "<h3>Data Brokers</h3><p>Third-party data brokers have been exposed selling sensitive personal information to various buyers.</p>"
    },

    // TECHNOLOGY - 25 articles
    {
        id: 76,
        title: "AI-Powered Security Tools Show Promise",
        category: "Technology",
        threat: "low",
        date: "2024-02-11",
        author: "Technology Innovation Team",
        excerpt: "AI security tools demonstrate significant improvements in threat detection.",
        icon: "🤖",
        content: "<h3>Research Findings</h3><p>AI-powered security tools show significant improvements in threat detection and response capabilities.</p>"
    },
    {
        id: 77,
        title: "Quantum Computing Threatens Current Encryption",
        category: "Technology",
        threat: "medium",
        date: "2024-02-10",
        author: "Quantum Security",
        excerpt: "Quantum computing poses threat to current encryption standards.",
        icon: "⚛️",
        content: "<h3>Quantum Threat</h3><p>Quantum computing development poses a significant threat to current encryption standards.</p>"
    },
    {
        id: 78,
        title: "Zero Trust Security Model Gains Adoption",
        category: "Technology",
        threat: "low",
        date: "2024-02-09",
        author: "Security Architecture",
        excerpt: "Zero trust security model adoption increases among enterprises.",
        icon: "🔐",
        content: "<h3>Zero Trust</h3><p>The zero trust security model is gaining adoption among enterprises for improved security posture.</p>"
    },
    {
        id: 79,
        title: "Blockchain Technology for Security Applications",
        category: "Technology",
        threat: "low",
        date: "2024-02-08",
        author: "Blockchain Security",
        excerpt: "Blockchain technology explored for security and authentication.",
        icon: "⛓️",
        content: "<h3>Blockchain Security</h3><p>Blockchain technology is being explored for security applications and authentication systems.</p>"
    },
    {
        id: 80,
        title: "Biometric Authentication Becomes Mainstream",
        category: "Technology",
        threat: "low",
        date: "2024-02-07",
        author: "Authentication Tech",
        excerpt: "Biometric authentication methods gain widespread adoption.",
        icon: "👆",
        content: "<h3>Biometric Auth</h3><p>Biometric authentication methods including fingerprint and facial recognition gain mainstream adoption.</p>"
    },
    {
        id: 81,
        title: "Passwordless Authentication Solutions Emerge",
        category: "Technology",
        threat: "low",
        date: "2024-02-06",
        author: "Auth Innovation",
        excerpt: "Passwordless authentication solutions reduce security risks.",
        icon: "🔑",
        content: "<h3>Passwordless Auth</h3><p>Passwordless authentication solutions emerge as safer alternatives to traditional passwords.</p>"
    },
    {
        id: 82,
        title: "Machine Learning Detects Anomalies",
        category: "Technology",
        threat: "low",
        date: "2024-02-05",
        author: "ML Security",
        excerpt: "Machine learning algorithms detect security anomalies.",
        icon: "🧠",
        content: "<h3>ML Detection</h3><p>Machine learning algorithms improve detection of security anomalies and suspicious behavior.</p>"
    },
    {
        id: 83,
        title: "Threat Intelligence Platforms Evolve",
        category: "Technology",
        threat: "low",
        date: "2024-02-04",
        author: "Threat Intel",
        excerpt: "Threat intelligence platforms provide real-time threat information.",
        icon: "📡",
        content: "<h3>Threat Intel</h3><p>Threat intelligence platforms evolve to provide real-time threat information and analysis.</p>"
    },
    {
        id: 84,
        title: "Security Automation Reduces Manual Work",
        category: "Technology",
        threat: "low",
        date: "2024-02-03",
        author: "Security Ops",
        excerpt: "Security automation reduces manual security operations work.",
        icon: "⚙️",
        content: "<h3>Security Automation</h3><p>Security automation tools reduce manual work in security operations centers.</p>"
    },
    {
        id: 85,
        title: "Containerization Security Challenges",
        category: "Technology",
        threat: "medium",
        date: "2024-02-02",
        author: "Container Security",
        excerpt: "Container security presents new challenges for DevOps teams.",
        icon: "📦",
        content: "<h3>Container Security</h3><p>Containerization introduces new security challenges that DevOps teams must address.</p>"
    },
    {
        id: 86,
        title: "Serverless Architecture Security",
        category: "Technology",
        threat: "medium",
        date: "2024-02-01",
        author: "Cloud Security",
        excerpt: "Serverless architectures require new security approaches.",
        icon: "☁️",
        content: "<h3>Serverless Security</h3><p>Serverless architectures require new security approaches and monitoring strategies.</p>"
    },
    {
        id: 87,
        title: "API Security Becomes Critical",
        category: "Technology",
        threat: "high",
        date: "2024-01-31",
        author: "API Security",
        excerpt: "API security becomes critical as APIs proliferate.",
        icon: "🔌",
        content: "<h3>API Security</h3><p>API security becomes increasingly critical as organizations expose more APIs to external consumers.</p>"
    },
    {
        id: 88,
        title: "Microservices Security Complexity",
        category: "Technology",
        threat: "medium",
        date: "2024-01-30",
        author: "Architecture Security",
        excerpt: "Microservices architecture increases security complexity.",
        icon: "🏗️",
        content: "<h3>Microservices</h3><p>Microservices architecture increases security complexity with more attack surfaces.</p>"
    },
    {
        id: 89,
        title: "DevSecOps Integration Improves Security",
        category: "Technology",
        threat: "low",
        date: "2024-01-29",
        author: "DevOps Security",
        excerpt: "DevSecOps integration improves security in development pipelines.",
        icon: "🔄",
        content: "<h3>DevSecOps</h3><p>DevSecOps integration improves security by incorporating security into development pipelines.</p>"
    },
    {
        id: 90,
        title: "Cloud Security Posture Management Tools",
        category: "Technology",
        threat: "low",
        date: "2024-01-28",
        author: "Cloud Security",
        excerpt: "CSPM tools help manage cloud security configurations.",
        icon: "☁️",
        content: "<h3>CSPM Tools</h3><p>Cloud security posture management tools help organizations manage cloud security configurations.</p>"
    },
    {
        id: 91,
        title: "Extended Detection and Response (XDR)",
        category: "Technology",
        threat: "low",
        date: "2024-01-27",
        author: "Detection Tech",
        excerpt: "XDR platforms provide comprehensive threat detection.",
        icon: "🎯",
        content: "<h3>XDR Platforms</h3><p>Extended detection and response platforms provide comprehensive threat detection across multiple layers.</p>"
    },
    {
        id: 92,
        title: "Security Orchestration Automation Response",
        category: "Technology",
        threat: "low",
        date: "2024-01-26",
        author: "Security Ops",
        excerpt: "SOAR platforms automate security incident response.",
        icon: "🤖",
        content: "<h3>SOAR Platforms</h3><p>Security orchestration automation and response platforms automate incident response workflows.</p>"
    },
    {
        id: 93,
        title: "Identity and Access Management Evolution",
        category: "Technology",
        threat: "low",
        date: "2024-01-25",
        author: "IAM Security",
        excerpt: "IAM solutions evolve with modern security requirements.",
        icon: "👤",
        content: "<h3>IAM Evolution</h3><p>Identity and access management solutions evolve to meet modern security requirements.</p>"
    },
    {
        id: 94,
        title: "Privileged Access Management Advances",
        category: "Technology",
        threat: "low",
        date: "2024-01-24",
        author: "PAM Security",
        excerpt: "PAM solutions provide better control of privileged access.",
        icon: "👑",
        content: "<h3>PAM Advances</h3><p>Privileged access management solutions provide better control and monitoring of privileged access.</p>"
    },
    {
        id: 95,
        title: "Endpoint Detection and Response Maturity",
        category: "Technology",
        threat: "low",
        date: "2024-01-23",
        author: "Endpoint Security",
        excerpt: "EDR solutions mature with advanced capabilities.",
        icon: "💻",
        content: "<h3>EDR Maturity</h3><p>Endpoint detection and response solutions mature with advanced threat hunting capabilities.</p>"
    },
    {
        id: 96,
        title: "Network Detection and Response Growth",
        category: "Technology",
        threat: "low",
        date: "2024-01-22",
        author: "Network Security",
        excerpt: "NDR solutions gain adoption for network threat detection.",
        icon: "🌐",
        content: "<h3>NDR Growth</h3><p>Network detection and response solutions gain adoption for detecting network-based threats.</p>"
    },
    {
        id: 97,
        title: "Deception Technology for Threat Detection",
        category: "Technology",
        threat: "low",
        date: "2024-01-21",
        author: "Deception Tech",
        excerpt: "Deception technology detects attackers through honeypots.",
        icon: "🍯",
        content: "<h3>Deception Tech</h3><p>Deception technology uses honeypots and decoys to detect and analyze attacker behavior.</p>"
    },
    {
        id: 98,
        title: "Vulnerability Management Automation",
        category: "Technology",
        threat: "low",
        date: "2024-01-20",
        author: "Vuln Management",
        excerpt: "Automated vulnerability management improves patch management.",
        icon: "🔧",
        content: "<h3>Vuln Automation</h3><p>Automated vulnerability management improves identification and remediation of vulnerabilities.</p>"
    },
    {
        id: 99,
        title: "Security Awareness Training Effectiveness",
        category: "Technology",
        threat: "low",
        date: "2024-01-19",
        author: "Security Training",
        excerpt: "Security awareness training reduces human security errors.",
        icon: "📚",
        content: "<h3>Security Training</h3><p>Security awareness training programs reduce human security errors and improve security culture.</p>"
    },
    {
        id: 100,
        title: "Incident Response Planning and Preparation",
        category: "Technology",
        threat: "low",
        date: "2024-01-18",
        author: "Incident Response",
        excerpt: "Incident response planning reduces breach impact.",
        icon: "🚨",
        content: "<h3>Incident Response</h3><p>Comprehensive incident response planning and preparation reduces the impact of security breaches.</p>"
    }
];
